<?php /** @var array $staff, $lines; @var float $revenue, $pct, $commission; @var string $from, $to, $salon, $currency */ ?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    * { font-family: DejaVu Sans, sans-serif; }
    body { color: #1f2937; font-size: 12px; margin: 0; }
    .head { border-bottom: 2px solid #db2777; padding-bottom: 12px; margin-bottom: 18px; }
    .head h1 { margin: 0 0 2px; font-size: 20px; color: #111827; }
    .head .sub { color: #6b7280; font-size: 11px; }
    .meta { width: 100%; margin-bottom: 18px; }
    .meta td { padding: 2px 0; vertical-align: top; }
    .meta .label { color: #6b7280; width: 110px; }
    table.lines { width: 100%; border-collapse: collapse; margin-top: 6px; }
    table.lines th { background: #f9fafb; text-align: left; padding: 7px 8px; font-size: 10px; text-transform: uppercase; letter-spacing: .04em; color: #6b7280; border-bottom: 1px solid #e5e7eb; }
    table.lines td { padding: 7px 8px; border-bottom: 1px solid #f3f4f6; }
    table.lines td.r, table.lines th.r { text-align: right; }
    .totals { margin-top: 16px; width: 280px; float: right; }
    .totals td { padding: 5px 8px; }
    .totals .grand { background: #fdf2f8; font-weight: bold; font-size: 14px; color: #be185d; border-top: 2px solid #db2777; }
    .foot { clear: both; margin-top: 60px; color: #9ca3af; font-size: 10px; border-top: 1px solid #e5e7eb; padding-top: 8px; }
    .sign { margin-top: 50px; }
    .sign td { width: 50%; padding-top: 30px; }
    .sign .line { border-top: 1px solid #9ca3af; padding-top: 4px; color: #6b7280; font-size: 10px; }
</style>
</head>
<body>
    <div class="head">
        <h1><?= esc($salon) ?></h1>
        <div class="sub">Commission Payout Statement</div>
    </div>

    <table class="meta">
        <tr>
            <td class="label">Stylist</td><td><strong><?= esc($staff['full_name']) ?></strong> <?= $staff['role'] ? '· ' . esc($staff['role']) : '' ?></td>
            <td class="label">Period</td><td><?= esc(date('M j, Y', strtotime($from))) ?> — <?= esc(date('M j, Y', strtotime($to))) ?></td>
        </tr>
        <tr>
            <td class="label">Commission rate</td><td><?= number_format($pct, 1) ?>%</td>
            <td class="label">Generated</td><td><?= esc(date('M j, Y H:i')) ?></td>
        </tr>
    </table>

    <table class="lines">
        <thead>
            <tr>
                <th>Date</th>
                <th>Invoice</th>
                <th>Customer</th>
                <th class="r">Amount (<?= esc($currency) ?>)</th>
            </tr>
        </thead>
        <tbody>
            <?php if (empty($lines)): ?>
                <tr><td colspan="4" style="text-align:center;color:#9ca3af;padding:20px;">No paid services in this period.</td></tr>
            <?php endif; ?>
            <?php foreach ($lines as $l): ?>
                <tr>
                    <td><?= esc(date('M j, Y', strtotime($l['paid_at']))) ?></td>
                    <td><?= esc($l['invoice_code'] ?? '—') ?></td>
                    <td><?= esc($l['customer_name'] ?: 'Walk-in') ?></td>
                    <td class="r"><?= number_format((float)$l['amount'], 2) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <table class="totals">
        <tr><td>Gross revenue</td><td class="r"><?= esc($currency) ?> <?= number_format($revenue, 2) ?></td></tr>
        <tr><td>Commission rate</td><td class="r"><?= number_format($pct, 1) ?>%</td></tr>
        <tr class="grand"><td>Payout due</td><td class="r"><?= esc($currency) ?> <?= number_format($commission, 2) ?></td></tr>
    </table>

    <table class="sign">
        <tr>
            <td><div class="line">Stylist signature</div></td>
            <td><div class="line">Authorised by</div></td>
        </tr>
    </table>

    <div class="foot">
        Generated by <?= esc($salon) ?> · This statement summarises commission earned on services paid within the period shown.
    </div>
</body>
</html>
